const Types = {
  GET_LOCAL_DATE: "GET_LOCAL_DATE",
  GET_LOCAL_YEAR: "GET_LOCAL_YEAR",
  GET_LOCAL_MONTH_STR: "GET_LOCAL_MONTH_STR",
  GET_LOCAL_MONTH_NUM: "GET_LOCAL_MONTH_NUM",
  GET_COUNT_DAYS_IN_MONTH: "GET_COUNT_DAYS_IN_MONTH",
  TOGGLE_MODAL: "TOGGLE_MODAL",
  GET_CURRENT_DAY_IN_MONTH: "GET_CURRENT_DAY_IN_MONTH",
};

export default Types;
